spring:
  application:
    name: exemploddd
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: "jdbc:mysql://localhost:3306/exemploddd?useSSL=false&allowPublicKeyRetrieval=true"
    username: crane
    password: 1234
    driverClassName: com.mysql.jdbc.Driver